const generalChartComponent = defineAsyncComponent(() => import('./GeneralChartProps.vue'));
const borderChartComponent = defineAsyncComponent(() => import('./BorderChartProps.vue'));
const textChartComponent = defineAsyncComponent(() => import('./TextChartProps.vue'));
const mapChartComponent = defineAsyncComponent(() => import('./MapChartProps.vue'));

const propsComponent = {
    'basic-bar': generalChartComponent,
    'horizontal-bar': generalChartComponent,
    'stacked-bar': generalChartComponent,
    'capsule-bar': generalChartComponent,
    'line-bar': generalChartComponent,
    'percent-bar': generalChartComponent,
    'basic-line': generalChartComponent,
    'area-line': generalChartComponent,
    'smooth-line': generalChartComponent,
    'basic-pie': generalChartComponent,
    'ring-pie': generalChartComponent,
    'rose-pie': generalChartComponent,
    'rotate-pie': generalChartComponent,
    'basic': generalChartComponent,
    'radar': generalChartComponent,
    'basic-scatter': generalChartComponent,
    'basic-radar': generalChartComponent,
    'multiple-radar': generalChartComponent,
    'basic-funnel': generalChartComponent,
    'polar-bar': generalChartComponent,
    'polar-line': generalChartComponent,
    'basic-gauge': generalChartComponent,
    'dynamic-gauge': generalChartComponent,
    'basic-progress': generalChartComponent,
    'dynamic-progress': generalChartComponent,
    'borderA': borderChartComponent,
    'borderB': borderChartComponent,
    'borderC': borderChartComponent,
    'borderD': borderChartComponent,
    'borderDresvse': borderChartComponent,
    'borderE': borderChartComponent,
    'borderEresvse': borderChartComponent,
    'borderF': borderChartComponent,
    'borderG': borderChartComponent,
    'borderH': borderChartComponent,
    'borderHresvse': borderChartComponent,
    'borderI': borderChartComponent,
    'borderJ': borderChartComponent,
    'borderK': borderChartComponent,
    'borderL': borderChartComponent,
    'borderM': borderChartComponent,
    'decorateA': borderChartComponent,
    'decorateB': borderChartComponent,
    'decorateBresvse': borderChartComponent,
    'decorateC': borderChartComponent,
    'decorateD': borderChartComponent,
    'decorateDresvse': borderChartComponent,
    'decorateE': borderChartComponent,
    'decorateF': borderChartComponent,
    'decorateG': borderChartComponent,
    'decorateH': borderChartComponent,
    'decorateHresvse': borderChartComponent,
    'decorateI': borderChartComponent,
    'decorateJ': borderChartComponent,
    'decorateK': borderChartComponent,
    'decorateL': borderChartComponent,
    'text': textChartComponent,
    'map-world': mapChartComponent,
    'map-china': mapChartComponent,
    'map-beijing': mapChartComponent,
    'map-tianjin': mapChartComponent,
    'map-hebei': mapChartComponent,
    'map-shanxi': mapChartComponent,
    'map-neimenggu': mapChartComponent,
    'map-liaoning': mapChartComponent,
    'map-jilin': mapChartComponent,
    'map-heilongjiang': mapChartComponent,
    'map-shanghai': mapChartComponent,
    'map-jiangsu': mapChartComponent,
    'map-zhejiang': mapChartComponent,
    'map-anhui': mapChartComponent,
    'map-fujian': mapChartComponent,
    'map-jiangxi': mapChartComponent,
    'map-shandong': mapChartComponent,
    'map-henan': mapChartComponent,
    'map-hubei': mapChartComponent,
    'map-hunan': mapChartComponent,
    'map-guangdong': mapChartComponent,
    'map-guangxi': mapChartComponent,
    'map-hainan': mapChartComponent,
    'map-chongqing': mapChartComponent,
    'map-sichuan': mapChartComponent,
    'map-guizhou': mapChartComponent,
    'map-yunnan': mapChartComponent,
    'map-xizang': mapChartComponent,
    'map-shaanxi': mapChartComponent,
    'map-gansu': mapChartComponent,
    'map-qinghai': mapChartComponent,
    'map-ningxia': mapChartComponent,
    'map-xinjiang': mapChartComponent,
    'map-taiwan': mapChartComponent,
    'map-hongkong': mapChartComponent,
    'map-aomen': mapChartComponent,
}
export const getPropsPanel = (type: string): Component | null => {
    if (type in propsComponent) {
        return propsComponent[type as keyof typeof propsComponent];
    }
    return null;
}
