/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChartRenderer: typeof import('./components/dashboard/renderers/BarChartRenderer.vue')['default']
    BorderChartProps: typeof import('./components/dashboard/propsPanel/BorderChartProps.vue')['default']
    BorderRenderer: typeof import('./components/dashboard/renderers/BorderRenderer.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    DecorateRenderer: typeof import('./components/dashboard/renderers/DecorateRenderer.vue')['default']
    DictTag: typeof import('./components/DictTag/index.vue')['default']
    DraggableResizableBlock: typeof import('./components/dashboard/blocks/DraggableResizableBlock.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    GeneralChartProps: typeof import('./components/dashboard/propsPanel/GeneralChartProps.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default']
    IFrame: typeof import('./components/iFrame/index.vue')['default']
    InuptNumber: typeof import('./components/InuptNumber/index.vue')['default']
    MapChartProps: typeof import('./components/dashboard/propsPanel/MapChartProps.vue')['default']
    MapChartRenderer: typeof import('./components/dashboard/renderers/MapChartRenderer.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RightToolbar: typeof import('./components/RightToolbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./components/Screenfull/index.vue')['default']
    SizeSelect: typeof import('./components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TextChartProps: typeof import('./components/dashboard/propsPanel/TextChartProps.vue')['default']
    TextRenderer: typeof import('./components/dashboard/renderers/TextRenderer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
