/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChartProps: typeof import('./components/dashboard/propsPanel/BarChartProps.vue')['default']
    BarChartRenderer: typeof import('./components/dashboard/renderers/BarChartRenderer.vue')['default']
    BasicEcharts: typeof import('./components/BaseCharts/basicEcharts.vue')['default']
    BoderRenderer: typeof import('./components/dashboard/renderers/BoderRenderer.vue')['default']
    BorderChartProps: typeof import('./components/dashboard/propsPanel/BorderChartProps.vue')['default']
    BorderRenderer: typeof import('./components/dashboard/renderers/BorderRenderer.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    DecorateRenderer: typeof import('./components/dashboard/renderers/DecorateRenderer.vue')['default']
    DictTag: typeof import('./components/DictTag/index.vue')['default']
    DraggableResizableBlock: typeof import('./components/dashboard/blocks/DraggableResizableBlock.vue')['default']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    FunnelChartProps: typeof import('./components/dashboard/propsPanel/FunnelChartProps.vue')['default']
    GaugeChartProps: typeof import('./components/dashboard/propsPanel/gaugeChartProps.vue')['default']
    GeneralChartProps: typeof import('./components/dashboard/propsPanel/GeneralChartProps.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default']
    IFrame: typeof import('./components/iFrame/index.vue')['default']
    InuptNumber: typeof import('./components/InuptNumber/index.vue')['default']
    LineChartProps: typeof import('./components/dashboard/propsPanel/LineChartProps.vue')['default']
    MapChartProps: typeof import('./components/dashboard/propsPanel/MapChartProps.vue')['default']
    MapChartRenderer: typeof import('./components/dashboard/renderers/MapChartRenderer.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    PieChartProps: typeof import('./components/dashboard/propsPanel/PieChartProps.vue')['default']
    PolarChartProps: typeof import('./components/dashboard/propsPanel/PolarChartProps.vue')['default']
    ProgressChartProps: typeof import('./components/dashboard/propsPanel/ProgressChartProps.vue')['default']
    RadarChartProps: typeof import('./components/dashboard/propsPanel/RadarChartProps.vue')['default']
    RightToolbar: typeof import('./components/RightToolbar/index.vue')['default']
    RingChartProps: typeof import('./components/dashboard/propsPanel/RingChartProps.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChartProps: typeof import('./components/dashboard/propsPanel/ScatterChartProps.vue')['default']
    Screenfull: typeof import('./components/Screenfull/index.vue')['default']
    SizeSelect: typeof import('./components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TextChartProps: typeof import('./components/dashboard/propsPanel/TextChartProps.vue')['default']
    TextRenderer: typeof import('./components/dashboard/renderers/TextRenderer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
